site_name: Project Documentation
site_description: Automatically converted Word documents with images
site_author: Your Team

# Documentation directory settings
docs_dir: docs
site_dir: site

# Theme settings
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extension settings
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - admonition
  - toc:
      permalink: true

# Plugin settings
plugins:
  - search

# Navigation structure
# This part will be automatically generated during build, but can be manually adjusted
nav:
  - Home: index.md
  # Additional items will be added automatically during build

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Copyright information
copyright: Copyright &copy; 2025