name: Full Documentation Pipeline

on:
  # Only allow manual trigger
  workflow_dispatch:
    inputs:
      deploy_docs:
        description: 'Deploy documentation to GitHub Pages'
        required: false
        type: boolean
        default: false

jobs:
  # Step 1: Run tests
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Verify environment
        run: |
          # Check directory structure
          mkdir -p docs/word
          mkdir -p docs/markdown
          mkdir -p docs/images
          
          # Check dependencies
          if ! npm list mammoth &>/dev/null; then
            echo "::error::mammoth dependency is missing, please install it"
            exit 1
          fi
          
          echo "Environment verification successful"

  # Step 2: Convert documents
  convert:
    name: Convert Documents
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run conversion
        run: node simplified-automation.js
      
      - name: Validate conversion
        run: |
          echo "Generated Markdown files:"
          ls -la docs/markdown/
          
          echo "Extracted image files:"
          ls -la docs/images/
          
          # Check if files were generated
          if [ -z "$(ls -A docs/markdown/)" ]; then
            echo "::error::No Markdown files were generated!"
            exit 1
          fi
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated-docs
          path: |
            docs/markdown/
            docs/images/
          retention-days: 7
      
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add docs/markdown/*.md
          git add docs/images/*
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Convert Word documents to Markdown and extract images [skip ci]"
            git push
          fi
