name: Markitdown Document Conversion

on:
  push:
    branches: [ dev ]  # Automatic trigger for dev branch
  workflow_dispatch:   # Manual trigger for main branch
    inputs:
      force_convert:
        description: 'Force document conversion'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  check_documents:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: check and upate the current files
        id: check
        run: |
          result=$(python .github/workflows/scripts/get_current_documents.py)
          echo "changed=$result"
          echo "changed=$result" >> "$GITHUB_OUTPUT"

          if [ "$result" = 'True' ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add docs/documents_snapshot.json
            git diff --quiet && git diff --staged --quiet || git commit -m "Update documents snapshot"
            git push
          else
            echo "No changes detected in docs/ directory"
          fi

  convert_documents:
    needs: check_documents
    if: needs.check_documents.outputs.changed == 'True'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          git clone https://github.com/microsoft/markitdown.git
          cd markitdown
          python -m pip install --upgrade pip
          pip install -e 'packages/markitdown[all]'

      - name: Run convert script
        run: python .github/workflows/scripts/documents_to_md.py

      - name: upate markdownfiles
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/markitdown
          git diff --quiet && git diff --staged --quiet || git commit -m "Update markdowns"
          git push
      